ballerina-platform/module-ballerinax-microsoft.outlook.mail

- outlookmail/Module.md
- outlookmail/Package.md
> $subject
> Providing proper documentation
- 
> Ballerina Swan Lake Alpha5
> [SL Alpha5] Change documentation structure

- outlookmail/Module.md
- outlookmail/Package.md
> $subject
> Providing proper documentation
- 
> Ballerina Swan Lake Beta2
> [SL Beta2] Change documentation structure

- README.md
- outlookmail/Module.md
- outlookmail/Package.md
- outlookmail/client.bal
- outlookmail/samples/sendMessage.bal
> $subject
> Ballerina Swan Lake Alpha5
> [SLAlpha5] Add documentation structure changes

- README.md
- outlookmail/Module.md
- outlookmail/Package.md
- outlookmail/client.bal
- outlookmail/samples/sendMessage.bal
> $subject
> Ballerina Swan Lake Beta2
> Add documentation structure changes

- README.md
- outlookmail/Dependencies.toml
- outlookmail/Package.md
- Bump version to slbeta3 in Dependencies.toml, README.md and Package.md
- Add missing Dependencies.toml
JDK 11
Ballerina SLBeta3-SNAPSHOT
> Bump versions for slbeta3 in master branch

- outlookmail/tests/test.bal
> Fixing testing failures happening occasionally.
Fixes https://github.com/wso2-enterprise/choreo/issues/7506 
- Unit tests 
> done
> Ballerina Swan Lake Beta3
> Fix test case failing issue

- gradle.properties
- outlookmail/Dependencies.toml
$title
JDK 11
Ballerina SLBeta3
> Bump dependency versions for Ballerina SLBeta3

- outlookmail/tests/test.bal
- Fix https://github.com/wso2-enterprise/choreo/issues/7855
JDK 11
Ballerina SLBeta3
> [SLBeta3] Add stream related changes in test cases

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- README.md
- outlookmail/Dependencies.toml
Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
- Add slbeta4 migration changes
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11
> Add slbeta4 migration changes

- outlookmail/streams.bal
- outlookmail/tests/test.bal
- outlookmail/utils.bal
fix build warning issues
```
Compiling source
ballerinax/googleapis.people:2.0.0
WARNING [tests/main_test.bal:(72:9,74:12)] unused variable 'e'
WARNING [tests/main_test.bal:(123:9,125:12)] unused variable 'e'
WARNING [utils.bal:(204:13,204:104)] unused variable 'streams'
WARNING [utils.bal:(213:13,213:102)] unused variable 'getContacts'
WARNING [utils.bal:(247:17,247:108)] unused variable 'streams'
WARNING [utils.bal:(284:17,284:108)] unused variable 'streams'
WARNING [utils.bal:(321:17,321:118)] unused variable 'streams'
```
- fix build warning issues
* Ballerina Version: slbeta6rc1
* Operating System: ubuntu
* Java SDK: Java11
> fix warning issues

- README.md
- build.gradle
- gradle.properties
- outlookmail/Ballerina.toml
- outlookmail/Dependencies.toml
- outlookmail/Package.md
- Bump version to `2.1.0`
- Update Ballerina version to `SLBeta6` in Package.md 
- Regenerate Dependencies.toml with `SLBeta6`
- Add `distribution = "slbeta6"` in Ballerina.toml
> Prepare for 2.1.0 release with SLBeta6

- outlookmail/Dependencies.toml
- Update Dependencies.toml with latest standard library versions
> Re-generate Dependencies.toml with latest pack

- gradle.properties
- outlookmail/Ballerina.toml
- outlookmail/Dependencies.toml
- outlookmail/Package.md
> Prepare for 2.2.0 release

- outlookmail/Ballerina.toml
- outlookmail/Dependencies.toml
- outlookmail/client.bal
- outlookmail/tests/test.bal
- outlookmail/utils.bal
Fixing the sendMessage function issue when attempting to send mail without attachments.
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/361
- Fixing sendMessage function attachement related issue.
Please delete options that are not relevant.
- All tests passed
* Ballerina Version: SwanLake 2021.0.2
* Operating System: Ubuntu 
* Java SDK: JDK 11
> Fix the sendMessage function attachments issue

- .github/workflows/pull-request.yml
- outlookmail/config-types.bal
- outlookmail/utils.bal
- Remove `clientConfig` from `OAuth2RefreshTokenGrantConfig`
> Remove clientConfig from RefreshTokenGrantConfig

- outlookmail/types.bal
- outlookmail/utils.bal
> Update http version

- README.md
- outlookmail/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/474
> Update Slack channel occurrences with Discord

- outlookmail/Ballerina.toml
- outlookmail/Dependencies.toml
- outlookmail/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475
> Update to Ballerina version 2201.3.0

- ballerina/tests/test.bal
$title
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/574
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
- One line describing the feature/improvement/fix made by this PR 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
> Fix test failure

- ballerina/tests/test.bal
$title.
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
- One line describing the feature/improvement/fix made by this PR 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
> Fix `testCreateMailSearchFolder` test failure
